import type { Metadata } from "next";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import ThemeProvider from "@/components/ThemeProvider";
import Toaster from "@/components/Toaster";
import fonts from "@/lib/fonts";
import "./globals.css";
import { cn } from "tailwind-variants";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      className={cn(fonts, "scrollbar-none")}
    >
      <body className="h-full min-h-screen w-full bg-stone-50 font-normal font-sans text-base text-stone-600 leading-normal antialiased">
        <ThemeProvider
          enableSystem
          disableTransitionOnChange
          defaultTheme="system"
        >
          <ReactQueryProvider>
            {children}
            <Toaster />
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
